# Generated by Django 5.2.3 on 2025-07-01 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationName', models.CharField(max_length=50, unique=True)),
                ('PlannedCount1', models.IntegerField(default=0)),
                ('PlannedCount2', models.IntegerField(default=0)),
                ('PlannedCount3', models.IntegerField(default=0)),
                ('ActualCount', models.IntegerField(default=0)),
                ('Efficiency', models.FloatField(default=0.0)),
                ('ipAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('Topic', models.CharField(blank=True, max_length=100, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('isalive', models.BooleanField(default=True)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('totalDowntime', models.FloatField(default=0.0)),
                ('calltype_index_map', models.TextField(default='{"PMD":0,"Quality":2,"Store":6,"JMD":8,"Production":12}')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift1_start', models.TimeField(default='05:30')),
                ('shift1_end', models.TimeField(default='14:20')),
                ('shift2_start', models.TimeField(default='14:20')),
                ('shift2_end', models.TimeField(default='00:10')),
                ('shift3_start', models.TimeField(default='00:10')),
                ('shift3_end', models.TimeField(default='05:30')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftData',
            fields=[
                ('StationName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stations.baydetail', to_field='StationName')),
                ('last_actual_count', models.IntegerField(default=0)),
                ('shift1_actual', models.IntegerField(default=0)),
                ('shift2_actual', models.IntegerField(default=0)),
                ('shift3_actual', models.IntegerField(default=0)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TodayDate', models.DateField()),
                ('Plan', models.IntegerField(default=0)),
                ('ActualCount', models.IntegerField(default=0)),
                ('Efficiency', models.FloatField(default=0.0)),
                ('mDowntime', models.FloatField(default=0.0)),
                ('pDowntime', models.FloatField(default=0.0)),
                ('qDowntime', models.FloatField(default=0.0)),
                ('sDowntime', models.FloatField(default=0.0)),
                ('jDowntime', models.FloatField(default=0.0)),
                ('totalDowntime', models.FloatField(default=0.0)),
                ('shift', models.IntegerField(null=True)),
                ('StationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.baydetail', to_field='StationName')),
            ],
        ),
        migrations.CreateModel(
            name='SectionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calltype', models.CharField(max_length=20)),
                ('FaultTime', models.DateTimeField(blank=True, null=True)),
                ('ResolvedTime', models.DateTimeField(blank=True, null=True)),
                ('DateTime', models.DateTimeField(blank=True, null=True)),
                ('Shift', models.IntegerField(blank=True, null=True)),
                ('StationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.baydetail', to_field='StationName')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftBaselines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Shift', models.IntegerField()),
                ('Date', models.DateField()),
                ('BaselineCount', models.IntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('StationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.baydetail', to_field='StationName')),
            ],
            options={
                'unique_together': {('StationName', 'Shift', 'Date')},
            },
        ),
    ]
